version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-ecr: circleci/aws-ecr@8.1.0
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  build-app:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: App Build
          command: |     
            docker build -t sampleapp:latest .
      - deploy:
              name: push application docker image
              command: |
                login="$(aws ecr get-login)" \
                ${login} \
                aws ecr describe-repositories --repository-names sampleapp --region eu-west-1 || aws ecr create-repository --repository-name sampleapp --region us-east-1 \
                docker tag 1.0.0:latest "${AWS_ECR_ACCOUNT_URL}/sampleapp:sampleapp-1.0.0" \
                docker push "${AWS_ECR_ACCOUNT_URL}/sampleapp:sampleapp-1.0.0"
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - build-app