version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build container image
          command: |
            # Build the container image
            ls -lrt
            docker build -t my-image .

      - run:
          name: Login to AWS ECR
          command: |
            # Authenticate with AWS ECR
            $(aws ecr get-login --no-include-email --region us-east-1)

      - run:
          name: Push container image to ECR
          command: |
            # Tag the container image and push it to ECR
            REPOSITORY_URL=$(aws ecr describe-repositories --repository-names my-repository --region us-east-1 | jq -r '.repositories[0].repositoryUri')
            docker tag my-image:latest $REPOSITORY_URL:latest
            docker push $REPOSITORY_URL:latest 

